require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/AbcSize:                  { Enabled: false }
Metrics/BlockLength:              { Enabled: false }
Metrics/ClassLength:              { Enabled: false }
Metrics/CyclomaticComplexity:     { Enabled: false }
Metrics/MethodLength:             { Enabled: false }
Metrics/PerceivedComplexity:      { Enabled: false }
Style/FrozenStringLiteralComment: { Enabled: false } # Not useful for Ruby 3.1 and above, which is what this gem targets

Gemspec/DependencyVersion:      { Enabled: true }
Lint/HeredocMethodCallPosition: { Enabled: true }
Lint/NumberConversion:          { Enabled: true }
Naming/InclusiveLanguage:       { Enabled: true }
Style/AutoResourceCleanup:      { Enabled: true }
Style/CollectionMethods:        { Enabled: true }

RSpec/NestedGroups:         { Enabled: false }
RSpec/ExampleLength:        { Enabled: false }
RSpec/MultipleExpectations: { Enabled: false }
