require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Lint/AssignmentInCondition:       { Enabled: false }
Metrics/AbcSize:                  { Enabled: false }
Metrics/BlockLength:              { Enabled: false }
Metrics/ClassLength:              { Enabled: false }
Metrics/CyclomaticComplexity:     { Enabled: false }
Metrics/MethodLength:             { Enabled: false }
Metrics/PerceivedComplexity:      { Enabled: false }
Style/FrozenStringLiteralComment: { Enabled: false }
Style/NumericPredicate:           { Enabled: false }

Layout/LineLength:
  Max: 120


RSpec/NestedGroups:         { Enabled: false }
RSpec/ExampleLength:        { Enabled: false }
RSpec/MultipleExpectations: { Enabled: false }
