name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.4.1'
          - '3.3.6'
          - '3.2.6'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Ensure that .yard/README is up-to-date
      run: bundle exec rake ensure_yard_readme_is_up_to_date
    - name: Run the default task
      run: bundle exec rake
